### ISSUE TITLE
Welcome!

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/AppStatTrento#8]
Welcome to Applied Statistics for High-Throughput Biology at the University of Trento. Please use this "Issue" to introduce yourself, using your new Github account.

**Comment by azufre451** [comment]
Hello everybody,

I am Moreno, I am a PhD student at the Laboratory of Computational Metagenomics at CIBIO. My background is a mix of computer science (Bachelor) and Biotechnology (Master). I am attending my first year!

**Comment by andrewmaltezthomas** [comment]
Hello everyone, 

I am Andrew, a visiting PhD student at the Laboratory of Computational Metagenomics at CIBIO. My background is also mixed, I did a bachelors in Biology, masters in oncology and now am doing a PhD in Bioinformatics at the University of São Paulo. I'm in my 3rd year.

**Comment by lucamasera** [comment]
Hello everybody,
I am Luca, I am a PhD student at the department of computer science here in Trento. My PhD is focused on the application of machine learning to Biology. I'm in my 2nd year.

**Comment by Dilaray** [comment]
Hello,

I am Dilara, I am a PhD student at Biomedicine and Biotechnology Department in Udine. I am a visitor PhD student here. My background based on genetics (B.Sc Genetics and Bioengineering; M.Sc. Bioengineering) and I am quite new at Bioinformatics and this is my first year.

**Comment by duhantoparlak** [comment]
It's Duhan, 2nd year PhD student at CIBIO, Prof. Sheref Mansy's Lab. My research covers cell-free synthetic biology and origins of life questions. I have a Bachelor in Biology and Master's in Chemical Engineering.

**Comment by Simonedet** [comment]
Hi,
finally here! I'm Simone, 1st year PhD student at CIBIO (lab Michela Denti). I work mainly with microRNAs and I am interested in finding microRNAs as biomarkers from liquid biopsies of cancer patients. My background is molecular biology.

**Comment by seunitn** [comment]
Hi,
I am Stephanie, I work in Marie-Laure Baudet's lab and I come from a experimental biology background with some additional bioinformatics training.

**Comment by fonz1983** [comment]
Hi, I am Alfonso, I work in the group of microbial genomics, I have some R experience but I am not a pro... At the moment I work on both comparative genomics of bacteria and metagenomics, I mainly use R for statistics and graphics, but I know that there is a whole world that I am missing. Therefore I am looking forward to attend the course and I am very curious about it.
