### ISSUE TITLE
Welcome to UNIVR Applied Statistics for High-Throughput Biology 2018

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/AppStatTrento#9]
Welcome! Please login to github.com and introduce yourself here, so I can connect names with GitHub IDs.

**Comment by maddahi93** [comment]
Hi I'm Fabio, a student of master degree in Medical Bioinformatics and I'm waiting the introduction of my classmates! :)

**Comment by lucag95** [comment]
Hello, I'm Luca.
See you on Tuesday 6!

**Comment by gioalb** [comment]
Hi :) 
I'm Giovanni, student of Medical Bioinformatics... see you on tuesday

**Comment by hejans** [comment]
Hi, I'm Davide and I'm attending Medical Bioinformatics course.

**Comment by SaraBosticardo** [comment]
Hi! I'm Sara, a student of master degree in Medical Bioinformatics...see you at lesson!

**Comment by RicciAle** [comment]
Hi! I'm Alessandro, student of the master degree in Medical Bioinformatics! See you tomorrow!

**Comment by elisalg** [comment]
Hi! I'm Elisa ,first year's student of master degree in Medical Bioinformatics! See you tomorrow at lesson!

**Comment by NarayananFiruza** [comment]
Hi! I'm Nicola, student of the master degree in Medical Bioinformatics! See you tomorrow!

**Comment by DavideDeToffol** [comment]
Hi! I'm Davide, student of the master degree in Medical Bioinformatics! See you tomorrow!

**Comment by SegatoElena** [comment]
Hi! I'm Elena, student of Medical Bioinformatics. See you tomorrow!

**Comment by giulialopatriello** [comment]
Hi!I'm Giulia,student of Medical Bioinformatics.
